# Generated by Django 4.1.7 on 2023-03-17 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.TextField()),
                ('country_code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coal', models.TextField()),
                ('oil', models.TextField()),
                ('gas', models.TextField()),
                ('cement', models.TextField()),
                ('flaring', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TotalEmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('total', models.FloatField()),
                ('coal', models.FloatField()),
                ('oil', models.FloatField()),
                ('gas', models.FloatField()),
                ('cement', models.FloatField()),
                ('flaring', models.FloatField()),
                ('percapita', models.FloatField()),
                ('country_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totalemission', to='emission.country')),
            ],
        ),
        migrations.CreateModel(
            name='PerCapitaEmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('coal', models.FloatField()),
                ('oil', models.FloatField()),
                ('gas', models.FloatField()),
                ('cement', models.FloatField()),
                ('flaring', models.FloatField()),
                ('country_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percapitaemission', to='emission.country')),
                ('totalpc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totalpercapita', to='emission.totalemission')),
            ],
        ),
    ]
