# Generated by Django 4.1.7 on 2023-03-28 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('country_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TotalEmission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('total', models.FloatField()),
                ('coal', models.FloatField()),
                ('oil', models.FloatField()),
                ('gas', models.FloatField()),
                ('cement', models.FloatField()),
                ('flaring', models.FloatField()),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emission.country')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('coal', models.TextField()),
                ('oil', models.TextField()),
                ('gas', models.TextField()),
                ('cement', models.TextField()),
                ('flaring', models.TextField()),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emission.country')),
            ],
        ),
        migrations.CreateModel(
            name='PerCapitaEmission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('percapita', models.FloatField()),
                ('coal', models.FloatField()),
                ('oil', models.FloatField()),
                ('gas', models.FloatField()),
                ('cement', models.FloatField()),
                ('flaring', models.FloatField()),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emission.country')),
            ],
        ),
    ]
