# Generated by Django 4.1.7 on 2023-03-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='percapitaemission',
            name='totalpc',
        ),
        migrations.RemoveField(
            model_name='totalemission',
            name='percapita',
        ),
        migrations.AddField(
            model_name='percapitaemission',
            name='percapita',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='percapitaemission',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='source',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='totalemission',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
