# Generated by Django 4.1.7 on 2023-03-23 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emission', '0002_remove_country_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emission.country'),
        ),
        migrations.AddField(
            model_name='source',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
