# Generated by Django 4.1.7 on 2023-03-31 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emission', '0002_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Source',
        ),
    ]
